### ISSUE TITLE
Eclipse throw errors on pom.xml

### ISSUE THREAD

**Issue by zhengye1** [mrin9/Angular2_SpringBoot#11]
![image](https://user-images.githubusercontent.com/5428784/31027023-b631749a-a516-11e7-82b3-83b93df1dda6.png)

After I import your project into eclipse, it getting me this highlighted error, I don't know what is causing on that, and don't know how to solve it... (Probably that related to the old issue I submit before that failed on build)

**Comment by mrin9** [comment]
I havent tested the project on eclipse.  But  maven-download-plugin is optional for this project. It is to just download the latest version of [Redoc](https://github.com/Rebilly/ReDoc). for REST API documentation.

You dont need that coz the API documentation for this project is also available with swagger. So try to comment the plugin and build. It will work
