### ISSUE TITLE
importing project in eclipse

### ISSUE THREAD

**Issue by danishaer** [mrin9/Angular2_SpringBoot#2]
refer to the closed issue -> "Lombock annotations for setters and getters are throwing errors"

After installing Lombock, all but one errors are resolved. The last error remains in the pom.xml.
the error message is:
"No marketplace entries found to handle download-maven-plugin:1.3.0:wget in Eclipse.  Please see Help for more information."
The error is on this tag -> "execution"

**Comment by danishaer** [comment]
the error is resolved by enclosing the "plugins" tags with a "pluginManagement" tag.

ref. to
http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

**Comment by mrin9** [comment]
thanks for figuring this out, I am open to accept a pull-request if you are willing to provide the new pom.xml file that worked for you.  That way I can record your contribution

**Comment by danishaer** [comment]
thanks. i have raised the pull request.

**Comment by mrin9** [comment]
merged - thanks for your contribution
