### ISSUE TITLE
Lazy Loading Loading Data till 20 Costumers

### ISSUE THREAD

**Issue by agarwalamit662** [mrin9/Angular2_SpringBoot#21]
The Customers are only loading till 20 size. Bottom onScroll has a problem.

The temporary solution that i have used is :- 

if (Math.abs(document.body.scrollHeight - (window.scrollY + window.innerHeight)) <= 100){
             this.bottom.emit(true);
 }

**Comment by mrin9** [comment]
Thanks for helping out on this, the previous code worked on chrome but not on firefox. with your fix it works on firefox too !!!.
