### ISSUE TITLE
Warinings while npm install

### ISSUE THREAD

**Issue by shamal** [mrin9/Angular2_SpringBoot#24]
When I do `npm install` i get the following. What should I do? 
If I install the dependancies it becomes cyclic. (i.e. when I install @angular/core@^4.3.0 another module requires @angular/core@5.x)

> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN @angular/compiler-cli@5.1.2 requires a peer of typescript@>=2.4.2 <2.6 but none is installed. You must install peer dependencies yourself.
> npm WARN tsickle@0.25.6 requires a peer of typescript@>=2.4.2 <2.6 but none is installed. You must install peer dependencies yourself.
> npm WARN clarity-angular@0.10.20 requires a peer of @angular/common@^4.3.0 but none is installed. You must install peer dependencies yourself.
> npm WARN clarity-angular@0.10.20 requires a peer of @angular/compiler@^4.3.0 but none is installed. You must install peer dependencies yourself.
> npm WARN clarity-angular@0.10.20 requires a peer of @angular/core@^4.3.0 but none is installed. You must install peer dependencies yourself.
> npm WARN clarity-angular@0.10.20 requires a peer of @angular/forms@^4.3.0 but none is installed. You must install peer dependencies yourself.
> npm WARN clarity-angular@0.10.20 requires a peer of @angular/platform-browser@^4.3.0 but none is installed. You must install peer dependencies yourself.
> npm WARN clarity-angular@0.10.20 requires a peer of @angular/platform-browser-dynamic@^4.3.0 but none is installed. You must install peer dependencies yourself.
> npm WARN clarity-angular@0.10.20 requires a peer of @angular/router@^4.3.0 but none is installed. You must install peer dependencies yourself.
> npm WARN clarity-ui@0.10.20 requires a peer of bootstrap@4.0.0-alpha.5 but none is installed. You must install peer dependencies yourself.

**Comment by mrin9** [comment]
none is error, all are warnings. You can ignore them for now. vmware clarity components will shortly be moving to angular 5 therefore they are care-full enough to not use any angular 4 feature which is depricated in angular 5. For the typescript warning you can downgrade typescript to 2.6. Personally I did not encounter any error using 2.6.2
