### ISSUE TITLE
Material Design Conversion

### ISSUE THREAD

**Issue by ershad1** [mrin9/Angular2_SpringBoot#27]
Hi,
This is a great site. It help me understand a lot of thing about angular. But I only love material design. I would love to have a branch of this in material design.

Please consider a brunch of material design and only angular and material design dependency no third party library please. I would love to contribute in material design conversion with your guidance rather than fork it and do it on my own.
  
  And with mysql db and better user management and role base ui access.

**Comment by mrin9** [comment]
If you fork this project and implement two examples of using 
 - lazy-loaded data table and (customers page)
 - virtual-repeat data table (orders page)

then I will contribute and convert the whole app into material design
