### ISSUE TITLE
CRUD screen exmple will make this complete

### ISSUE THREAD

**Issue by bhikyagolu** [mrin9/Angular2_SpringBoot#31]
CRUD screen exmple will make this complete. May be Employee/Customer/Product/Order

**Comment by mrin9** [comment]
cant allow create update and delete as I am hosting this project, and the data will get messed up if it is allowed to change

**Comment by bhikyagolu** [comment]
But as an example one dummy model can be done right ..it will complete as whole example application
list with search option
view
edit delete and new screen.
Consider this as this is pain area for many starter developers

**Comment by Cuiqs76** [comment]
hope add CRUD.  If you are afraid of data messed, you can restore data every once in a while.

**Comment by mrin9** [comment]
The issue is when multiple users access the app at the same time. they can mess-up each others data and create confusion. I do not intend to provide that feature now. 
But checkout my other project https://github.com/mrin9/Modular-Java-Jersey-Vue 
This has all the CRUD feature.
