### ISSUE TITLE
老哥，你的用户我和密码是多少，登录不了呀

### ISSUE THREAD

**Issue by ReExia** [mrin9/Angular2_SpringBoot#33]

**Comment by milang-org** [comment]
demo   demo
admin   admin
user   user
jowens3   jowens3
kburns4   kburns4
jshaw5   jshaw5

**Comment by mrin9** [comment]
Try the  [Heroku](https://infomud.herokuapp.com/#/login)  instance it is slow to start, takes long time to start. 
I have fixed the google cloud instance too now

**Comment by Cuiqs76** [comment]
use demo can not login

**Comment by mrin9** [comment]
This has been restored now. The API server went down
ThanksMrin    On Thursday, November 22, 2018, 12:46:55 AM PST, Cuiqs76 <notifications@github.com> wrote:  
 
 
use demo can not login
