### ISSUE TITLE
Feature Request: Remove # from url

### ISSUE THREAD

**Issue by bhikyagolu** [mrin9/Angular2_SpringBoot#38]
Remove # from url
make all link bookmarkable. Refresh url should be able to process through index,html

**Comment by mrin9** [comment]
all links are bookmarkable with '#' too and pages can be refreshed. Let me know what issue are you facing and steps to reproduce.

Removing hash from URL involves some work to bypass spring security and server redirection too. this will complicate the security process a little bit so avoiding it for now
