### ISSUE TITLE
dev environment for front end

### ISSUE THREAD

**Issue by danishaer** [mrin9/Angular2_SpringBoot#4]
hi.

i was using augury for angular 2 to degub the frontend.
augury does not support angular 4. can u help me setting up the dev env for frontend.

thanks

**Comment by mrin9** [comment]
chromes vanilla devtools of chrome to debug. I used VS-Code debugger too, but returned back to chrome debugger, Thats better suited for front-end debugging. 
I am sorry cant help you with augury. May be they will start supporting ng4 soon
