### ISSUE TITLE
Unresolved compilation problems: 

### ISSUE THREAD

**Issue by wurangbo** [mrin9/Angular2_SpringBoot#5]
hi guy, when i run the app, it got an Unresolved compilation problems.
2017-04-17 15:16:07.144 ERROR 23964 --- [nio-9119-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.Error: Unresolved compilation problems: 
	The method getUsername() is undefined for the type Login
	The method getUsername() is undefined for the type Login
	The method getPassword() is undefined for the type Login
	The method getFirstName() is undefined for the type User
	The method setToken(String) is undefined for the type SessionResponse
	The method getFirstName() is undefined for the type User
	The method getLastName() is undefined for the type User
	The method getEmail() is undefined for the type User
	The method setToken(String) is undefined for the type SessionResponse

**Comment by mrin9** [comment]
I just tested it by deploying it on heroku and it works fine for me. You can access it at 
[https://infomud.herokuapp.com](https://infomud.herokuapp.com)
since its working on free hosting you need to wait for about 1 min to startup

Let me know your build steps and how are you running it. If i spot any issues there I can tell you

**Comment by wurangbo** [comment]
hi guy, I have solved the issues yesterday. it need we generate getter and setter for model class.

**Comment by mrin9** [comment]
Glad, you figured it out. By the way The project uses org.projectlombok (lombok) to auto generate getters and setters. You dont have to generate it yourself. However if you imported the project in eclipse and trying to build from there  then try to follow this [issue](https://github.com/mrin9/Angular-SpringBoot-REST-JWT/issues/1)

**Comment by OusmaneNdong** [comment]
Optional<BookingEntity> findAllBookings(String userId, LocalDate appointmentDate, String slot);

i need the query of this method

**Comment by OusmaneNdong** [comment]
Optional<BookingEntity> findAllBookings(String userId, LocalDate appointmentDate, String slot);
