### ISSUE TITLE
Not Able to Validate the user in Case of MongoDB

### ISSUE THREAD

**Issue by rrohitesh** [mrin9/Angular2_SpringBoot#7]
Hello, 

I am trying to using your JWT token by writing a demo program .I am using mongodb. The problem is my DB is not getting called. Please suggest what all changes required in order to use mongodb.

**Comment by mrin9** [comment]
cannot comment unless i see some code and where you might be facing the problem. 

Are you having the problem with the filters in the original source code ?
if you want to validate your user against other database then you should modify it [here](https://github.com/mrin9/Angular-SpringBoot-REST-JWT/blob/master/src/main/java/com/app/identity/UserDetailsService.java#L29)

You must configure to start and stop mongodb service as the springboot starts and stop. 
The app uses ORM technologies to talk to databases, so it cannot talk to a document store like mongo.
