### ISSUE TITLE
How to store password in encoded format and validate during login

### ISSUE THREAD

**Issue by rrohitesh** [mrin9/Angular2_SpringBoot#8]
Hello,

I am new to spring security  and i am learning.Can you please tell me how to store the password into some encoded format and validate it during login.

**Comment by mrin9** [comment]
if you want to encode then use Base64, if you want to encrypt then there are many choices, pick something that suites you.

for storing it in the database and retrieving from it. 
first create an API that takes plaintext and returns encoded value and vice versa.
now use this api in various database read and write commands
