### ISSUE TITLE
Remember me functionality

### ISSUE THREAD

**Issue by maroil** [mrin9/Angular2_SpringBoot#9]
First of all thank you for the example.
I was wondering if you can suggest a way to implement Remember Me functionality using JWT ?

**Comment by mrin9** [comment]
JWT is just a token that has its own expiry data after which the token is not valid anymore. 
If you want to stretch this thing to support Remember me then you should first generate a token that has a fairly big expiry date maybe like some date in 2020 and then store a map of user-name and the token in browser's local-storage. Once the user enters his/her username use the locally stored map to retrieve the token and use it in various REST calls

but I will not recommend this process as it creates a large surface for security attacks. JWTs are like keys, if someone get hold of it then they can have access to all  your REST calls, therefore JWTs are created with a very small expiry date such as for 15 mins and then they become invalid.
